name: Build Packages

on:
  push:
    branches:
      - main  # 如果您使用的是 master 分支，将 "main" 改为 "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create deb directory
        run: mkdir -p debs  # 确保有一个 debs 目录

      - name: Install dpkg-dev
        run: sudo apt-get install -y dpkg-dev

      - name: Build Packages file
        run: |
          # 假设您的 .deb 文件位于 debs 目录下
          dpkg-scanpackages ./debs > Packages

      - name: Compress Packages file
        run: bzip2 Packages

      - name: Commit and push Packages files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.bz2
          git commit -m "Update Packages and Packages.bz2"
          git push
