name: Build Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create deb directory
        run: mkdir -p debs

      - name: Install dpkg-dev
        run: sudo apt-get update && sudo apt-get install -y dpkg-dev

      - name: List debs directory for debugging
        run: ls -alh ./debs  # 列出 debs 目录中的文件

      - name: Build Packages file
        run: |
          dpkg-scanpackages ./debs /dev/null | gzip -9c > Packages.gz

      - name: List files before compressing
        run: ls -alh  # 列出当前目录中的文件以调试

      - name: Compress Packages file
        run: |
          if [ -f Packages ]; then
            bzip2 Packages
          else
            echo "Packages file not found!"
            exit 1
          fi

      - name: Check git status
        run: git status

      - name: Commit and push Packages files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Packages Packages.bz2 Packages.gz
          git commit -m "Update Packages and Packages.bz2" || echo "No changes to commit"
          git push
